#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 0
    enable_tabline_ft_icon = true

    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    enable_statusline_bfpath = true
    enable_statusline_mode = true

    windows_index_type = 0

    automatic_update = false
    guifont = "SauceCodePro Nerd Font Mono:h11"
    vimcompatible = true
    bootstrap_after = "myspacevim#after"
    bootstrap_before = "myspacevim#before"
    relativenumber = false
    statusline_unicode_symbols = true
    default_indent = 2

    enable_cursorcolumn = true
    enable_vimfiler_welcome = false

    filetree_direction = "left"
    

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = "colorscheme"

[[layers]]
  name = "lang#lua"
[[layers]]
  name = "lang#plantuml"
[[layers]]
  name = "lang#xml"

[[layers]]
  name = "format"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#sh"
  

[[layers]]
  name = "incsearch"

[[custom_plugins]]
  repo = "vim-scripts/dbext.vim"
  merged = 0

[[custom_plugins]]
  repo = "ybian/smartim"
